gorproxyd

diff --git a/gorproxyd b/gorproxyd
--- a/gorproxyd
+++ b/gorproxyd
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ `id -u` -ne "0" ]; then
+    echo "ERROR: Permission denied." 1>&2
+    exit 1
+fi
+
 start() {
     gorproxy &
 }
